### ISSUE TITLE
[Project] URL Shortener

### ISSUE THREAD

**Issue by Ashesh3** [GitHub-Campus-Program-India/CIS#16]
### Did you attend the GitHub Workshop?

- [X] I have attended the GitHub Workshop

### Project Name

URL Shortener

### Project Repository

https://github.com/Ashesh3/url-shortener

### Project URL

https://shrturl.us.to/

### University Name

Shri Shankaracharya Institute of Professional Management

### Project Description

This is a URL Shortening Service hosted on Azure, Built with NodeJS using ExpressJS framework and MongoDB as the database backend.
This service can be used to shorten long URLs on the web and share them easily.
It also tracks the total number of hits a particular URL gets on the site.
The homepage keeps track of all the short links you make across devices (using the I.P).
It helps you easily short and share long URLs to your friends on any messaging or social media platform.

Live Demo: https://shrturl.us.to/

![](https://user-images.githubusercontent.com/3626859/141315732-78f00051-523b-4bb7-bfee-1da053005edb.png)

**Developer Pack Tools Used:**

- Azure: For hosting the backend
- GitHub: For managing repo and commits
- ATOM: For writing the source code
- MongoDB: Clusters to host the database

### GitHub Student Developer Pack Tools Used

Microsoft Azure, GitHub, ATOM, Mongo DB

**Comment by Surbhdey** [comment]
@Ashesh3 - Many congratulations 🎉 for wining the Hackathon. Kindly fill the [form](https://airtable.com/shrzge1Ok1EnxQPZV) for your Swag!!

**Comment by Ashesh3** [comment]
@Surbhdey Thank you so much! 😊I have filled the form!
